#include <msp430g2553.h>

#define LED_R BIT6
#define LED_V BIT0
#define BTN BIT3
#define BTN_E BIT2
//LAS SIGUIENTES TRES LÍNEAS SON PARA EL CONTROL DEL RGB
#define GREEN BIT3
#define RED BIT1
#define BLUE BIT5

void pasos(volatile unsigned int COLOR){
    //PASO 1
    P1OUT |= LED_V;
    while(P1IN != 0b00000101); //SOLO SALE DEL CICLO SI SE MANDA A CERO EL BIT3 (SWITCH DE LA TARGETA)
    while(P1IN != 0b00001101); //VA AL SIGUIENTE PASO AL SOLTAR EL PUSH BUTTON
    //PASO 2
    P1OUT ^= LED_V;
    P2OUT |= COLOR;
    //PASO3
    while(P1IN != 0b00001000); //SALE DEL CICLO SOLO SI SE MANDA A CERO EL BIT2 (SWICH EXTERNO)
    while(P1IN != 0b00001100); //VA AL SIGUIENTE PASO AL SOLTAR EL BOTÓN
    //PASO 4
    P2OUT ^= COLOR;
    P1OUT |= LED_R;
    //PASO 5
    while(P1IN != 0b01000000); //SALE DEL CICLO ÚNICAMENTE AL PRESIONAR AMBOS BOTONES
    while(P1IN != 0b01001100); //VA AL SIGUIENTE PASO AL SOLTAR LOS DOS BOTONES
    P1OUT ^= LED_R;

    /*
     * NOTA: COLOQUE DOBLE WHILE DEBIDO A QUE EN EL EJERCICIO EN CLASE DE SOLO PRENDER Y APAGAR LOS TRES LED CON UN SOLO PUSH BUTTON, SI MANTENIAS PRESIONADO RECORRIA TODO EL CICLO,
     * O SI NO LO SOLTABAS CON LA SUFICIENTE RAPIDEZ, SE SEGUIA AL ENCENDIDO Y APAGADO DE LOS DEMAS LED. ME PARECIO MAS EFICIENTE QUE HICIERA LOS CAMBIOS SOLO AL SOLTAR LOS BOTONES.
     * ASI NO HACE COSAS INDESEADAS
     */
}


void main(void)
{
	WDTCTL = WDTPW | WDTHOLD;	// stop watchdog timer

    P1OUT = 0; P2OUT = 0;
    P1DIR |= LED_R + LED_V;
    P2DIR |= GREEN + BLUE + RED;

    //HABILITAR RESISTENCIA PULLUP/PULLDOWN
    P1REN |= BTN | BTN_E;
    //CONFIGURAR EN MODO PULLLUP
    P1OUT |= BTN | BTN_E;

    while(1){
        pasos(GREEN | RED);
        pasos(BLUE | GREEN);
        pasos(BLUE | RED);
        pasos(BLUE | RED | GREEN);
    }

}
